### ISSUE TITLE
NPE When creating webhooks for Organisation folders

### ISSUE THREAD

**Issue by eschleining** [jenkinsci/gitlab-branch-source-plugin#146]
Somewhere after version 1.4.1 a NullPointer Exception was introduced, when creating webHooks for subprojects within an organisation folder.
To reproduce it, scan for subprojects within an organisation folder and confuigure that webhooks should be created.

Here is the log for this behavior:
[Thu Jun 10 14:26:37 CEST 2021] Starting organization scan...
[Thu Jun 10 14:26:37 CEST 2021] Updating actions...
Group URL: ...
[Thu Jun 10 14:26:40 CEST 2021] Consulting GitLab Group
Checking projects...

Checking project ...
ERROR: [Thu Jun 10 14:26:45 CEST 2021] Could not fetch sources from navigator io.jenkins.plugins.gitlabbranchsource.GitLabSCMNavigator@d87e8c0a
[Thu Jun 10 14:26:45 CEST 2021] Finished organization scan. Scan took 7.7 sec
FATAL: Failed to recompute children of ...
java.lang.NullPointerException
	at io.jenkins.plugins.gitlabbranchsource.GitLabSCMNavigator.visitSources(GitLabSCMNavigator.java:274)
	at jenkins.branch.OrganizationFolder.computeChildren(OrganizationFolder.java:542)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:278)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:165)
	at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:1031)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE

**Comment by alfredopalhares** [comment]
I am also having this problem while checking for new reposiotires on a gitlab. Our jenkins cannot read new repos. We did not change anything,

```
Checking project [myorg/mygroup/myrepo](https://gitlab.com/myorg)
ERROR: [Thu Sep 15 08:01:11 UTC 2022] Could not fetch sources from navigator io.jenkins.plugins.gitlabbranchsource.GitLabSCMNavigator@71abe6f8
[Thu Sep 15 08:01:11 UTC 2022] Finished organization scan. Scan took 4.2 sec
FATAL: Failed to recompute children of myorg / mygroup
java.lang.NullPointerException
	at io.jenkins.plugins.gitlabbranchsource.GitLabHookCreator.isTokenEqual(GitLabHookCreator.java:231)
	at io.jenkins.plugins.gitlabbranchsource.GitLabHookCreator.createWebHookWhenMissing(GitLabHookCreator.java:222)
	at io.jenkins.plugins.gitlabbranchsource.GitLabSCMNavigator.visitSources(GitLabSCMNavigator.java:283)
	at jenkins.branch.OrganizationFolder.computeChildren(OrganizationFolder.java:536)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:278)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:166)
	at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:918)
	at hudson.model.ResourceController.execute(ResourceController.java:107)
	at hudson.model.Executor.run(Executor.java:449)
Finished: FAILURE
```

We using jenkins version:  4.3.6
Gitlab API Plugin Version 5.0.1-78.v47a_45b_9f78b_7 
GitLab Branch Source Plugin Version 640.v7101b_1c0def9 

Any feedback would welcome!
