### ISSUE TITLE
webhook does not work, and the GitLabPushSCMEvent.isMatch method throw NullPointException

### ISSUE THREAD

**Issue by chenyan0107** [jenkinsci/gitlab-branch-source-plugin#163]
**Versions:**
Jenkins 2.268
GitLab 10.0.0
Gitlab API Plugin 1.0.6
GitLab Branch Source Plugin 1.5.10

Hello, thank you provide the very powerful plugin
but when i use to create multiple branches project, webhook does not worked.
Jenkins system log view as follows
`
handleEvent: X-Gitlab-Event=Push Hook

SCMEventListener.onSCMHeadEvent(SCMHeadEvent) jenkins.branch.OrganizationFolder$SCMEventListenerImpl@5e6377ad propagated an exception
java.lang.NullPointerException
	at io.jenkins.plugins.gitlabbranchsource.GitLabPushSCMEvent.isMatch(GitLabPushSCMEvent.java:75)
	at io.jenkins.plugins.gitlabbranchsource.AbstractGitLabSCMHeadEvent.isMatch(AbstractGitLabSCMHeadEvent.java:56)
	at jenkins.branch.OrganizationFolder$SCMEventListenerImpl.onSCMHeadEvent(OrganizationFolder.java:1139)
	at jenkins.scm.api.SCMHeadEvent$DispatcherImpl.fire(SCMHeadEvent.java:246)
	at jenkins.scm.api.SCMHeadEvent$DispatcherImpl.fire(SCMHeadEvent.java:229)
	at jenkins.scm.api.SCMEvent$Dispatcher.run(SCMEvent.java:505)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:67)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

in class GitLabPushSCMEvent, isMatch method throw NullPointException，

then i insert log in isMatch method,
payload project id is null.
so what should i do?
please help me !
Thank you!

`
@Override
public boolean isMatch(@NonNull GitLabSCMSource source) {

    LOGGER.info("project="+getPayload().getProject());

    LOGGER.info("sourceProjectId="+source.getProjectId());

    return getPayload().getProject().getId().equals(source.getProjectId());

}
`

logs
'
project={
  "id" : null,
  "name" : "xxx",
  "description" : "",
  "webUrl" : "http://xxxx/xxx/GitPipDemo",
  "avatarUrl" : null,
  "gitSshUrl" : "git@1xxx:xxxx/GitPipDemo.git",
  "gitHttpUrl" : "http://xxxx:xxxx/xxxx/GitPipDemo.git",
  "namespace" : "xxxx",
  "visibilityLevel" : 0,
  "pathWithNamespace" : "xxxx/GitPipDemo",
  "defaultBranch" : "feature/test",
  "ciConfigPath" : null
....
}
sourceProjectId=2
'

**Comment by chenyan0107** [comment]
I find the error reason!
it is my fail!  my Gitlab version is 10.0.0, to low
after upgrad Gitlab, fixed!
thank you!
