### ISSUE TITLE
Version 1.5.9 breaks gitlab notification for merge requests

### ISSUE THREAD

**Issue by dcendents** [jenkinsci/gitlab-branch-source-plugin#164]
With the plugin version 1.5.8 when a merge request was built in jenkins, the plugin would notify gitlab using the revision ref. Now gitlab could easily match the revision with any open merge request. That always worked for me.

Now with the plugin version 1.5.9, if I understand the modification correctly, it is trying to find the correct project id, I would assume in case the MR is from a fork. I can see in the code it parses the jenkins job name, split the string on character "-" and expect the last item of the split to be the merge request ID.

On some projects I have chosen the merge request build strategy "Both the current merge request revision and the merge request merged with the current target branch revision"

Which means for each merge request I get 2 jobs: MR-123-head and MR-123-merge.
Now with the blind string splitting it is trying to convert the strings head and merge to a number, fails to do so and it does not notify gitlab at all. At least it could revert to the previous strategy (revision ref) in that case.

```
java.lang.NumberFormatException: For input string: "head"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at io.jenkins.plugins.gitlabbranchsource.helpers.GitLabPipelineStatusNotifier.getSourceProjectId(GitLabPipelineStatusNotifier.java:213)
	at io.jenkins.plugins.gitlabbranchsource.helpers.GitLabPipelineStatusNotifier.sendNotifications(GitLabPipelineStatusNotifier.java:319)
	at io.jenkins.plugins.gitlabbranchsource.helpers.GitLabPipelineStatusNotifier.access$400(GitLabPipelineStatusNotifier.java:52)
	at io.jenkins.plugins.gitlabbranchsource.helpers.GitLabPipelineStatusNotifier$JobCheckOutListener.onCheckout(GitLabPipelineStatusNotifier.java:470)
```
```
java.lang.NumberFormatException: For input string: "merge"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at io.jenkins.plugins.gitlabbranchsource.helpers.GitLabPipelineStatusNotifier.getSourceProjectId(GitLabPipelineStatusNotifier.java:213)
	at io.jenkins.plugins.gitlabbranchsource.helpers.GitLabPipelineStatusNotifier.sendNotifications(GitLabPipelineStatusNotifier.java:319)
	at io.jenkins.plugins.gitlabbranchsource.helpers.GitLabPipelineStatusNotifier.access$400(GitLabPipelineStatusNotifier.java:52)
	at io.jenkins.plugins.gitlabbranchsource.helpers.GitLabPipelineStatusNotifier$JobCompletedListener.onCompleted(GitLabPipelineStatusNotifier.java:483)
```

### Reproduction steps

- Configure a project to use the Discover merge requests from origin strategy: Both the current merge request revision and the merge request merged with the current target branch revision
- Open a MR in gitlab, it will forever stay in the "Checking pipeline status" state

**Comment by jetersen** [comment]
released in [621.vd49608f876da_](https://github.com/jenkinsci/gitlab-branch-source-plugin/releases/tag/621.vd49608f876da_)
