### ISSUE TITLE
Empty Project list and SSL error : Connection Reset

### ISSUE THREAD

**Issue by stevemayster** [jenkinsci/gitlab-branch-source-plugin#278]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Windows 2016
 Gitlab Branch Source Plugin 644.va_a_66886e07b_5
 Gitlab API Plugin 5.0.1-78.v47a_45b_9f78b_7 
 Jenkins 2.383
GItlab EE  15  in Docker
 ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows 2016

### Reproduction steps

1. Install GItlab Branch Source Plugin
2. Add server and API token
3. Test connection successful  
4. Create multi branch pipeline and try to add Project
5. Got empty Project
6. Going to Jenkins log and found:
Exception caught:org.gitlab4j.api.GitLabApiException: javax.net.ssl.SSLProtocolException: Connection reset
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:165)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
Caused: javax.net.ssl.SSLProtocolException: Connection reset

### Expected Results

Project apperead in interface, scan  multibranch pipeline successfully 

### Actual Results

Empty Project in Branch Sources, error - javax.net.ssl.SSLProtocolException: Connection reset

**Comment by Turiok** [comment]
Hi @stevemayster,
Does your Gitlab use a self-signed SSL certificate?
If so, does your Java JVM contain the trusted certificates for your Gitlab?
