### ISSUE TITLE
[JENKINS-64814] GitLab Branch Source unable to download project avatar

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/gitlab-branch-source-plugin#690]
<h3><a name="Preconditions"></a>Preconditions</h3>
<ul>
	<li>Private GitLab project hosted @ <a href="https://gitlab.com" class="external-link" target="_blank" rel="nofollow noopener">https://gitlab.com</a></li>
</ul>

<h3><a name="Steps"></a>Steps</h3>
<ul>
	<li>Install Jenkins and Gitlab branch source plugin (versions mentioned in the environment field)</li>
	<li>Setup necessary credentials for GitLab integration (private token with API access && ssh creds.)</li>
	<li>Create a Multi branch pipeline</li>
	<li>Observe the logo/avatar displayed in the dashboard</li>
</ul>

<h3><a name="Outcome"></a>Outcome</h3>
<ul>
	<li>The logo/avatar seem to be a randomly generated one</li>
	<li>The logs show that the attempt to fetch project's logo fails

<pre>
Feb 07, 2021 10:16:48 PM INFO io.jenkins.plugins.gitlabbranchsource.helpers.GitLabAvatarCache$FetchImage call

Server returned HTTP response code: 401 <span class="code-keyword">for</span> URL: https:<span class="code-comment">//gitlab.com/uploads/-/system/project/avatar/XXXXXXXX/IMG.png
</span>java.io.IOException: Server returned HTTP response code: 401 <span class="code-keyword">for</span> URL: https:<span class="code-comment">//gitlab.com/uploads/-/system/project/avatar/XXXXXXXX/IMG.png
</span>	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3099)
	at java.base/java.net.URLConnection.getContentType(URLConnection.java:519)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentType(HttpsURLConnectionImpl.java:402)
	at io.jenkins.plugins.gitlabbranchsource.helpers.GitLabAvatarCache$FetchImage.call(GitLabAvatarCache.java:506)
Caused: java.io.IOException: Server returned HTTP response code: 401 <span class="code-keyword">for</span> URL: https:<span class="code-comment">//gitlab.com/uploads/-/system/project/avatar/XXXXXXXX/IMG.png
</span>	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at io.jenkins.plugins.gitlabbranchsource.helpers.GitLabAvatarCache$FetchImage.call(GitLabAvatarCache.java:513)
	at io.jenkins.plugins.gitlabbranchsource.helpers.GitLabAvatarCache$FetchImage.call(GitLabAvatarCache.java:490)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:834)
</pre></li>
</ul>

<h3><a name="Notes"></a>Notes</h3>
<ul>
	<li>The project builds normally otherwise and build status is correctly pushed to GitLab</li>
	<li>Trying the failing URL (from logs) in the browser actually provides the project logo/avatar</li>
</ul>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/ytux.png" title="ytux's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ytux">ytux</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-64814" target="_blank">GitLab Branch Source unable to download project avatar</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/baymac.svg" title="baymac's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=baymac">baymac</a>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>component(s)</b>: gitlab-branch-source-plugin
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 4
<li><b>watchers</b>: 6
<li><b>imported</b>: 20251216-182730
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<h3><a name="Preconditions"></a>Preconditions</h3>
<ul>
	<li>Private GitLab project hosted @ <a href="https://gitlab.com" class="external-link" target="_blank" rel="nofollow noopener">https://gitlab.com</a></li>
</ul>

<h3><a name="Steps"></a>Steps</h3>
<ul>
	<li>Install Jenkins and Gitlab branch source plugin (versions mentioned in the environment field)</li>
	<li>Setup necessary credentials for GitLab integration (private token with API access &amp;&amp; ssh creds.)</li>
	<li>Create a Multi branch pipeline</li>
	<li>Observe the logo/avatar displayed in the dashboard</li>
</ul>

<h3><a name="Outcome"></a>Outcome</h3>
<ul>
	<li>The logo/avatar seem to be a randomly generated one</li>
	<li>The logs show that the attempt to fetch project's logo fails
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Feb 07, 2021 10:16:48 PM INFO io.jenkins.plugins.gitlabbranchsource.helpers.GitLabAvatarCache$FetchImage call

Server returned HTTP response code: 401 <span class="code-keyword">for</span> URL: https:<span class="code-comment">//gitlab.com/uploads/-/system/project/avatar/XXXXXXXX/IMG.png
</span>java.io.IOException: Server returned HTTP response code: 401 <span class="code-keyword">for</span> URL: https:<span class="code-comment">//gitlab.com/uploads/-/system/project/avatar/XXXXXXXX/IMG.png
</span>	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3099)
	at java.base/java.net.URLConnection.getContentType(URLConnection.java:519)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentType(HttpsURLConnectionImpl.java:402)
	at io.jenkins.plugins.gitlabbranchsource.helpers.GitLabAvatarCache$FetchImage.call(GitLabAvatarCache.java:506)
Caused: java.io.IOException: Server returned HTTP response code: 401 <span class="code-keyword">for</span> URL: https:<span class="code-comment">//gitlab.com/uploads/-/system/project/avatar/XXXXXXXX/IMG.png
</span>	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at io.jenkins.plugins.gitlabbranchsource.helpers.GitLabAvatarCache$FetchImage.call(GitLabAvatarCache.java:513)
	at io.jenkins.plugins.gitlabbranchsource.helpers.GitLabAvatarCache$FetchImage.call(GitLabAvatarCache.java:490)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:834)
</pre>
</div></div></li>
</ul>

<h3><a name="Notes"></a>Notes</h3>
<ul>
	<li>The project builds normally otherwise and build status is correctly pushed to GitLab</li>
	<li>Trying the failing URL (from logs) in the browser actually provides the project logo/avatar</li>
</ul>
</pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Jenkins 2.263.3, GitLab Branch Source plugin 1.5.4 , GitLab 13.9.0-pre 80a6f1bf66f</code></li></ul>
<details><summary><i>1 attachment</i></summary>

- [image-2022-02-18-12-20-16-915.png](https://issues.jenkins.io/secure/attachment/57290/image-2022-02-18-12-20-16-915.png)
  > ![image-2022-02-18-12-20-16-915.png](https://issues.jenkins.io/secure/attachment/57290/image-2022-02-18-12-20-16-915.png)
</details>

**Comment by RomuAdq** [comment]
There is a new endpoint for this :

curl --header "PRIVATE-TOKEN: <your_access_token>" \
  --url "https://gitlab.example.com/api/v4/projects/4/avatar"

https://docs.gitlab.com/api/projects/#download-a-project-avatar
